name: Pre-Commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    uses: Mosher-Labs/.github/.github/workflows/pre-commit.yml@ef07cf67ff3b59d701ca4ebb5670f8579b0b0303 # v0.10.33
