name: Pre-Commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    uses: Mosher-Labs/.github/.github/workflows/pre-commit.yml@563ce006b6248edecdcbe134f3a4888b7d2595f5 # v0.10.37
