---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@563ce006b6248edecdcbe134f3a4888b7d2595f5" # v0.10.37
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
