---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@3915b3040bd9335819629478bc809511bc014c67" # v0.12.0
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
